### ISSUE TITLE
Bug with hesitant hindrance

### ISSUE THREAD

**Issue by alessio-barbone** [pelwer1/Deal-Init#8]
Hello!

First of all, thanks for this very helpful script: me and my players are really enjoying it!

By the way, it happened that a character with the hesitant hindrance drew a red joker and then a Jack of Clubs and the script kept the jack and discarded the joker.

I guess the problem it's at row 909:

https://github.com/pelwer1/Deal-Init/blob/18664ba50fed3fe1e309a48dcc29edd76ddd8582/1.4/Deal-Init.js#L909

Having:

nextcard.cardRank = 36 (Jack of Club)
turnorder[i].rank = 53 (Red Joker)

the condition will be met and the script will change the card instead of keeping the joker.

Hope it helps 😃

**Comment by pelwer1** [comment]
Thanks for the note.  I am seeing the right behavior from the script:
![HesHind](https://user-images.githubusercontent.com/13632571/100474905-9a7c5800-3096-11eb-835f-d2b2ee53a071.png)

It appears to be keeping the joker and choosing the worse card otherwise.

Can you give me a little more detail on the setup for the token and the situation?
* Did it have any other Init Edges besides Hesitant?
* Was it on Hold the previous round?
* Were you dealing to chat or dealing to a specific character? --deal2chat or --onlyto

The code in the lines above 909 catch the joker in my tests and do the right thing.

**Comment by alessio-barbone** [comment]
Hi! The problem raises when the first card is the joker, like in this screenshot:

<img width="514" alt="Schermata 2020-11-27 alle 19 58 24" src="https://user-images.githubusercontent.com/59878013/100478364-451e6600-30eb-11eb-94d5-021c3f24f79e.png">

I just use !deal-init and !deal-init --reset

**Comment by pelwer1** [comment]
Yep, you're right.  

I'll get to work on this...

**Comment by pelwer1** [comment]
Ok.  I think I got it fixed.  Please give r1.5 a try and let me know if it looks right to you.
https://github.com/pelwer1/Deal-Init

**Comment by alessio-barbone** [comment]
It seems a right fix to me.

Thank you 😃

**Comment by pelwer1** [comment]
Alessio,
I just submitted a pull request for v1.5 of Deal-Init with the Hesitant Hindrance fix to Roll20.  You should be able to get the bug fixed version from 1-click install on Tuesday or Wednesday this week.  Enjoy!  - Pat.

**Comment by alessio-barbone** [comment]
Thank you!
